version: '3.3'
services:
    f1tv-en:
        env_file:
            - .env
        environment:
            - LANGUAGE=eng
            - LIVE=true
            - RECORD=false
        image: 'htobi02/f1tv:${TAG:-latest}'
        labels:
          - "com.centurylinklabs.watchtower.scope=f1tv"
    f1tv-de:
        env_file:
            - .env
        environment:
            - LANGUAGE=deu
            - LIVE=true
            - RECORD=false
        image: 'htobi02/f1tv:${TAG:-latest}'
        labels:
          - "com.centurylinklabs.watchtower.scope=f1tv"
    f1tv-fx:
        env_file:
            - .env
        environment:
            - LANGUAGE=fx
            - LIVE=true
            - RECORD=false
        image: 'htobi02/f1tv:${TAG:-latest}'
        labels:
          - "com.centurylinklabs.watchtower.scope=f1tv"

    watchtower:
        image: containrrr/watchtower
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
        command: --interval 30 --scope f1tv
        labels:
          - "com.centurylinklabs.watchtower.scope=f1tv"
