version: '3.3'
services:
    f1tv:
        env_file:
            - .env
        image: 'htobi02/f1tv:${TAG:-latest}'
        labels:
          - "com.centurylinklabs.watchtower.scope=f1tv"

    watchtower:
        image: containrrr/watchtower
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
        command: --interval 30 --scope f1tv
        labels:
          - "com.centurylinklabs.watchtower.scope=f1tv"
